name: Dump the action environment as well as the Docker environment

on:
  workflow_dispatch:

jobs:
    update-license-year:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Dump environment
              run: |
                env
            - name: Dump Docker environment
              uses: ./local/dump-docker-env