name: Dump the action environment as well as the Docker environment

on:
  workflow_dispatch:

jobs:
    Dump-Environment:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Dump environment
              run: |
                env
            - name: Dump Docker environment
              uses: ./local